# Generated by Django 5.2.16 on 2026-07-18 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LadderTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True)),
                ('host_token', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('lobby', 'Lobby'), ('in_progress', 'En curso'), ('finished', 'Terminada')], default='lobby', max_length=20)),
                ('current_level_index', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='questions.questionset')),
                ('ladder_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='game.laddertemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50)),
                ('client_token', models.CharField(blank=True, max_length=64)),
                ('score', models.IntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.gamesession')),
            ],
            options={
                'ordering': ['-score', 'joined_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('points_awarded', models.IntegerField(default=0)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='game.player')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='questions.question')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='questions.answeroption')),
            ],
            options={
                'ordering': ['answered_at'],
            },
        ),
        migrations.CreateModel(
            name='PrizeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('points', models.PositiveIntegerField()),
                ('is_checkpoint', models.BooleanField(default=False)),
                ('ladder_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='game.laddertemplate')),
            ],
            options={
                'ordering': ['ladder_template', 'index'],
            },
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.UniqueConstraint(fields=('session', 'nickname'), name='unique_nickname_per_session'),
        ),
        migrations.AddConstraint(
            model_name='playeranswer',
            constraint=models.UniqueConstraint(fields=('player', 'question'), name='unique_answer_per_player_question'),
        ),
        migrations.AddConstraint(
            model_name='prizelevel',
            constraint=models.UniqueConstraint(fields=('ladder_template', 'index'), name='unique_level_index_per_ladder'),
        ),
    ]
