# Generated by Django 5.2.16 on 2026-07-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='channel_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
