# Generated by Django 5.2.16 on 2026-07-19 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_gamesession_is_paused_player_channel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado'), ('experto', 'Experto')], max_length=20),
        ),
    ]
